/*
Patch crée par Mathew
Traduction Creatures : 681
Dernière mise à jour du patch : Jamais
*/
SET NAMES utf8;

UPDATE `locales_creature` SET `name_loc2` = 'Loramus Thalipedes' WHERE `entry` = 7783;
UPDATE `locales_creature` SET `name_loc2` = 'Magus Rimtori' WHERE `entry` = 8578;
UPDATE `locales_creature` SET `name_loc2` = 'Hal McAllister' WHERE `entry` = 20342;
UPDATE `locales_creature` SET `name_loc2` = 'Elémentaire d\'eau' WHERE `entry` = 37994;
UPDATE `locales_creature` SET `name_loc2` = 'Cort Gorestein' WHERE `entry` = 24498;
UPDATE `locales_creature` SET `name_loc2` = 'Ilkrud Magthrull' WHERE `entry` = 3664;
UPDATE `locales_creature` SET `name_loc2` = 'Bubb Lazarr' WHERE `entry` = 27628;
UPDATE `locales_creature` SET `name_loc2` = 'Ethereal Ring Control Bunny' WHERE `entry` = 23424;
UPDATE `locales_creature` SET `name_loc2` = 'Finkle Einhorn' WHERE `entry` = 10776;
UPDATE `locales_creature` SET `name_loc2` = 'Ethereal Ring Target Bunny, Forge' WHERE `entry` = 23445;
UPDATE `locales_creature` SET `name_loc2` = 'Shleipnarr' WHERE `entry` = 8280;
UPDATE `locales_creature` SET `name_loc2` = 'Davil Crokford' WHERE `entry` = 10945;
UPDATE `locales_creature` SET `name_loc2` = 'Torkus Jr.' , `subname_loc2` = '' WHERE `entry` = 23365;
UPDATE `locales_creature` SET `name_loc2` = 'Tresa Farmountain' , `subname_loc2` = 'Survival Trainer' WHERE `entry` = 2801;
UPDATE `locales_creature` SET `name_loc2` = 'Arko\'narin' WHERE `entry` = 11018;
UPDATE `locales_creature` SET `name_loc2` = 'Rogg' , `subname_loc2` = '' WHERE `entry` = 37072;
UPDATE `locales_creature` SET `name_loc2` = 'Pachyderme rose au format pinte' WHERE `entry` = 24753;
UPDATE `locales_creature` SET `name_loc2` = 'Faucon-dragon saccage-soleil' WHERE `entry` = 35148;
UPDATE `locales_creature` SET `name_loc2` = 'Ruk Choqueur-martial' , `subname_loc2` = 'Maître de guerre' WHERE `entry` = 34976;
UPDATE `locales_creature` SET `name_loc2` = 'Magistère Dalhyr' , `subname_loc2` = 'Mage de bataille de Joug-d\'hiver' WHERE `entry` = 35603;
UPDATE `locales_creature` SET `name_loc2` = 'Mosha Corne-d\'étoile' , `subname_loc2` = 'Maître de guerre' WHERE `entry` = 34978;
UPDATE `locales_creature` SET `name_loc2` = 'Marinier réprouvé' WHERE `entry` = 36148;
UPDATE `locales_creature` SET `name_loc2` = 'Maître de guerre de l\'île des Conquérants' WHERE `entry` = 34437;
UPDATE `locales_creature` SET `name_loc2` = 'Worg de guerre d\'Argent' WHERE `entry` = 36558;
UPDATE `locales_creature` SET `name_loc2` = 'Cheval de guerre d\'Argent' WHERE `entry` = 35644;
UPDATE `locales_creature` SET `name_loc2` = 'Jaeren Ligesol' WHERE `entry` = 35004;
UPDATE `locales_creature` SET `name_loc2` = 'Champion de Darnassus' WHERE `entry` = 35332;
UPDATE `locales_creature` SET `name_loc2` = 'Monture de Jaelyne Chant-du-soir' WHERE `entry` = 34658;
UPDATE `locales_creature` SET `name_loc2` = 'Jaelyne Chant-du-soir' , `subname_loc2` = 'Grande championne de Darnassus' WHERE `entry` = 34657;
UPDATE `locales_creature` SET `name_loc2` = 'Monture de Lana Rudemartel' WHERE `entry` = 35636;
UPDATE `locales_creature` SET `name_loc2` = 'Champion de Forgefer' WHERE `entry` = 35329;
UPDATE `locales_creature` SET `name_loc2` = 'Monture du Maréchal Jacob Alerius' WHERE `entry` = 35637;
UPDATE `locales_creature` SET `name_loc2` = 'Champion de Hurlevent' WHERE `entry` = 35328;
UPDATE `locales_creature` SET `name_loc2` = 'Maréchal Jacob Alerius' , `subname_loc2` = 'Grand champion de Hurlevent' WHERE `entry` = 34705;
UPDATE `locales_creature` SET `name_loc2` = 'Jaeren Ligesol ressuscité' , `subname_loc2` = 'Serviteur du Chevalier noir' WHERE `entry` = 35545;
UPDATE `locales_creature` SET `name_loc2` = 'Monture d\'Ambrose Étinceboulon' WHERE `entry` = 35633;
UPDATE `locales_creature` SET `name_loc2` = 'Champion de Gnomeregan' WHERE `entry` = 35331;
UPDATE `locales_creature` SET `name_loc2` = 'Ambrose Étinceboulon' , `subname_loc2` = 'Grand champion de Gnomeregan' WHERE `entry` = 34702;
UPDATE `locales_creature` SET `name_loc2` = 'Saccageur kor\'kron' , `subname_loc2` = '' WHERE `entry` = 36164;
UPDATE `locales_creature` SET `name_loc2` = 'Capitaine de la canonnière de la Horde' WHERE `entry` = 35003;
UPDATE `locales_creature` SET `name_loc2` = 'Noceur orc fantomatique' WHERE `entry` = 35251;
UPDATE `locales_creature` SET `name_loc2` = 'Noceur troll fantomatique' WHERE `entry` = 35253;
UPDATE `locales_creature` SET `name_loc2` = 'Esprit de troll joyeux' WHERE `entry` = 34482;
UPDATE `locales_creature` SET `name_loc2` = 'Esprit d\'orc joyeux' WHERE `entry` = 34477;
UPDATE `locales_creature` SET `name_loc2` = 'Noceur humain fantomatique' WHERE `entry` = 35249;
UPDATE `locales_creature` SET `name_loc2` = 'Esprit d\'humain joyeux' WHERE `entry` = 34435;
UPDATE `locales_creature` SET `name_loc2` = 'Serissa Funèbricole' , `subname_loc2` = 'Démoniste' WHERE `entry` = 34474;
UPDATE `locales_creature` SET `name_loc2` = 'Shocuul' , `subname_loc2` = 'Guerrier' WHERE `entry` = 34475;
UPDATE `locales_creature` SET `name_loc2` = 'Champion de l\'Exodar' WHERE `entry` = 35330;
UPDATE `locales_creature` SET `name_loc2` = 'Monture de Colossos' WHERE `entry` = 35768;
UPDATE `locales_creature` SET `name_loc2` = 'Colossos' , `subname_loc2` = 'Grand champion de l\'Exodar' WHERE `entry` = 34701;
UPDATE `locales_creature` SET `name_loc2` = 'Souvenir de Lucifron' WHERE `entry` = 35031;
UPDATE `locales_creature` SET `name_loc2` = 'Souvenir d\'Ignis' WHERE `entry` = 35050;
UPDATE `locales_creature` SET `name_loc2` = 'Requin bleu de la mer Boréale' WHERE `entry` = 35061;
UPDATE `locales_creature` SET `name_loc2` = 'Requin mako de la mer Boréale' WHERE `entry` = 35071;
UPDATE `locales_creature` SET `name_loc2` = 'Requin renard de la mer Boréale' WHERE `entry` = 35060;
UPDATE `locales_creature` SET `name_loc2` = 'Malithas Brillelame' , `subname_loc2` = 'Paladin' WHERE `entry` = 34456;
UPDATE `locales_creature` SET `name_loc2` = 'Magistrice Caradess' , `subname_loc2` = 'Mage de bataille de Joug-d\'hiver' WHERE `entry` = 35612;
UPDATE `locales_creature` SET `name_loc2` = 'Anthar Soigneforge' , `subname_loc2` = 'Prêtre' WHERE `entry` = 34466;
UPDATE `locales_creature` SET `name_loc2` = 'Velanaa' , `subname_loc2` = 'Paladin' WHERE `entry` = 34465;
UPDATE `locales_creature` SET `name_loc2` = 'Kavina Chantebosquet' , `subname_loc2` = 'Druide' WHERE `entry` = 34460;
UPDATE `locales_creature` SET `name_loc2` = 'Touillert Vizitige' , `subname_loc2` = 'Mage' WHERE `entry` = 34468;
UPDATE `locales_creature` SET `name_loc2` = 'Irieth Pas-de-l\'ombre' , `subname_loc2` = 'Voleuse' WHERE `entry` = 34472;
UPDATE `locales_creature` SET `name_loc2` = 'Shaabad' , `subname_loc2` = 'Chaman' WHERE `entry` = 34463;
UPDATE `locales_creature` SET `name_loc2` = 'Kvaldir en colère' WHERE `entry` = 35072;
UPDATE `locales_creature` SET `name_loc2` = 'Souvenir de Delrissa' WHERE `entry` = 35043;
UPDATE `locales_creature` SET `name_loc2` = 'Saamul' , `subname_loc2` = 'Chaman' WHERE `entry` = 34470;
UPDATE `locales_creature` SET `name_loc2` = 'Melador Arpenteval' , `subname_loc2` = 'Druide' WHERE `entry` = 34469;
UPDATE `locales_creature` SET `name_loc2` = 'Tyrius Lamebrune' , `subname_loc2` = 'Chevalier de la mort' WHERE `entry` = 34461;
UPDATE `locales_creature` SET `name_loc2` = 'Alyssia Traquelune' , `subname_loc2` = 'Chasseur' WHERE `entry` = 34467;
UPDATE `locales_creature` SET `name_loc2` = 'Brienna Tombenuit' , `subname_loc2` = 'Prêtre' WHERE `entry` = 34473;
UPDATE `locales_creature` SET `name_loc2` = 'Barrett Ramsey' , `subname_loc2` = 'Maître du colisée d\'Argent' WHERE `entry` = 35895;
UPDATE `locales_creature` SET `name_loc2` = 'Noceur réprouvé fantomatique' WHERE `entry` = 35244;
UPDATE `locales_creature` SET `name_loc2` = 'Esprit de réprouvé joyeux' WHERE `entry` = 34476;
UPDATE `locales_creature` SET `name_loc2` = 'Noceur de Dalaran fantomatique' WHERE `entry` = 35254;
UPDATE `locales_creature` SET `name_loc2` = 'Esprit de Dalaran joyeux' WHERE `entry` = 35256;
UPDATE `locales_creature` SET `name_loc2` = 'Noceur elfe de sang fantomatique' WHERE `entry` = 35243;
UPDATE `locales_creature` SET `name_loc2` = 'Esprit d\'elfe de sang joyeux' WHERE `entry` = 34483;
UPDATE `locales_creature` SET `name_loc2` = 'Baelnor Portelumière' , `subname_loc2` = 'Paladin' WHERE `entry` = 34471;
UPDATE `locales_creature` SET `name_loc2` = 'Hippogriffe du Concordat argenté' WHERE `entry` = 35147;
UPDATE `locales_creature` SET `name_loc2` = 'Souvenir de Vek\'nilash' WHERE `entry` = 35036;
UPDATE `locales_creature` SET `name_loc2` = 'Cheval de guerre d\'Argent' WHERE `entry` = 35445;
UPDATE `locales_creature` SET `name_loc2` = 'Souvenir d\'Entropius' WHERE `entry` = 35044;
UPDATE `locales_creature` SET `name_loc2` = 'Souvenir de Vezax' WHERE `entry` = 35051;
UPDATE `locales_creature` SET `name_loc2` = 'Gardien immortel marqué' WHERE `entry` = 36064;
UPDATE `locales_creature` SET `name_loc2` = 'Souvenir d\'Archimonde' WHERE `entry` = 35041;
UPDATE `locales_creature` SET `name_loc2` = 'Forestier-sombre Vorel' WHERE `entry` = 37780;
UPDATE `locales_creature` SET `name_loc2` = 'Agent saccage-soleil' , `subname_loc2` = '' WHERE `entry` = 36776;
UPDATE `locales_creature` SET `name_loc2` = 'Magistère Arlan' , `subname_loc2` = 'Intendant des emblèmes de givre' WHERE `entry` = 37941;
UPDATE `locales_creature` SET `name_loc2` = 'Image du déconstructeur XT-002' WHERE `entry` = 37861;
UPDATE `locales_creature` SET `name_loc2` = 'Magistère Hathorel' , `subname_loc2` = 'Les Saccage-soleil' WHERE `entry` = 36670;
UPDATE `locales_creature` SET `name_loc2` = 'Surveillant kor\'kron' , `subname_loc2` = '' WHERE `entry` = 36213;
UPDATE `locales_creature` SET `name_loc2` = 'Forestier-sombre Cyndia' , `subname_loc2` = '' WHERE `entry` = 36226;
UPDATE `locales_creature` SET `name_loc2` = 'Forestier-sombre Clea' , `subname_loc2` = '' WHERE `entry` = 36224;
UPDATE `locales_creature` SET `name_loc2` = 'Forestier-sombre Anya' , `subname_loc2` = '' WHERE `entry` = 36225;
UPDATE `locales_creature` SET `name_loc2` = 'Arcturis' , `subname_loc2` = '' WHERE `entry` = 38453;
UPDATE `locales_creature` SET `name_loc2` = 'Veut des chemises' WHERE `entry` = 36944;
UPDATE `locales_creature` SET `name_loc2` = 'Veut des dessous' WHERE `entry` = 36946;
UPDATE `locales_creature` SET `name_loc2` = 'Veut de l\'eau' WHERE `entry` = 36947;
UPDATE `locales_creature` SET `name_loc2` = 'Chevalier de la Lame d\'ébène' , `subname_loc2` = '' WHERE `entry` = 38505;
UPDATE `locales_creature` SET `name_loc2` = 'Cheval de guerre d\'Argent' WHERE `entry` = 38500;
UPDATE `locales_creature` SET `name_loc2` = 'Croisé d\'argent' , `subname_loc2` = '' WHERE `entry` = 38493;
UPDATE `locales_creature` SET `name_loc2` = 'Commandant d\'argent' , `subname_loc2` = '' WHERE `entry` = 37965;
UPDATE `locales_creature` SET `name_loc2` = 'Commandant de la Lame d\'ébène' , `subname_loc2` = '' WHERE `entry` = 37967;
UPDATE `locales_creature` SET `name_loc2` = 'Veut des pantalons' WHERE `entry` = 36945;
UPDATE `locales_creature` SET `name_loc2` = 'Généralissime Tirion Fordring' , `subname_loc2` = '' WHERE `entry` = 37119;
UPDATE `locales_creature` SET `name_loc2` = 'Généralissime Darion Mograine' , `subname_loc2` = '' WHERE `entry` = 37120;
UPDATE `locales_creature` SET `name_loc2` = 'Lapin de forgerune' WHERE `entry` = 37702;
UPDATE `locales_creature` SET `name_loc2` = 'Champion d\'ébène' , `subname_loc2` = '' WHERE `entry` = 37996;
UPDATE `locales_creature` SET `name_loc2` = 'Champion d\'argent' , `subname_loc2` = '' WHERE `entry` = 37928;
UPDATE `locales_creature` SET `name_loc2` = 'Le roi-liche' WHERE `entry` = 38153;
UPDATE `locales_creature` SET `name_loc2` = 'Torgo l\'Ancien' , `subname_loc2` = '' WHERE `entry` = 38194;
UPDATE `locales_creature` SET `name_loc2` = 'Seigneur Gargamoelle' WHERE `entry` = 36612;
UPDATE `locales_creature` SET `name_loc2` = 'Canon de la canonnière de la Horde' WHERE `entry` = 36839;
UPDATE `locales_creature` SET `name_loc2` = 'Haut seigneur Saurcroc' WHERE `entry` = 37187;
UPDATE `locales_creature` SET `name_loc2` = 'Général kor\'kron' WHERE `entry` = 37189;
UPDATE `locales_creature` SET `name_loc2` = 'Le Damné' WHERE `entry` = 37011;
UPDATE `locales_creature` SET `name_loc2` = 'Le roi-liche' WHERE `entry` = 37181;
UPDATE `locales_creature` SET `name_loc2` = 'Alchimiste Finklestein' , `subname_loc2` = 'Intendant du Verdict des cendres' WHERE `entry` = 37687;
UPDATE `locales_creature` SET `name_loc2` = 'Ormus le Pénitent' , `subname_loc2` = 'Armures de chevalier de la mort' WHERE `entry` = 38316;
UPDATE `locales_creature` SET `name_loc2` = 'Croisé Halford' , `subname_loc2` = 'Armures de paladin' WHERE `entry` = 37696;
UPDATE `locales_creature` SET `name_loc2` = 'Scott le Miséricordieux' , `subname_loc2` = 'Armures de prêtre' WHERE `entry` = 38054;
UPDATE `locales_creature` SET `name_loc2` = 'Goodman « Tope-la ! »' , `subname_loc2` = 'Intendant des emblèmes de givre' WHERE `entry` = 38858;
UPDATE `locales_creature` SET `name_loc2` = 'Croisé Langue-sinistre' , `subname_loc2` = 'Armures de guerrier' WHERE `entry` = 37688;
UPDATE `locales_creature` SET `name_loc2` = 'Gardien lié par la mort' WHERE `entry` = 37007;
UPDATE `locales_creature` SET `name_loc2` = 'Ancien soldat squelettique' WHERE `entry` = 37012;
UPDATE `locales_creature` SET `name_loc2` = 'Furia' , `subname_loc2` = 'Niveau 80 Mort-vivant ' WHERE `entry` = 37586;
UPDATE `locales_creature` SET `name_loc2` = 'Haragg l\'Invisible' , `subname_loc2` = 'Armures de démoniste' WHERE `entry` = 38181;
UPDATE `locales_creature` SET `name_loc2` = 'Martin Victus' WHERE `entry` = 37580;
UPDATE `locales_creature` SET `name_loc2` = 'Uvlus Plaie-de-feu' , `subname_loc2` = 'Armures de mage' WHERE `entry` = 38284;
UPDATE `locales_creature` SET `name_loc2` = 'Ikfirus le Vil' , `subname_loc2` = 'Armures de voleur' WHERE `entry` = 37991;
UPDATE `locales_creature` SET `name_loc2` = 'Vol\'guk' , `subname_loc2` = 'Armures de chaman' WHERE `entry` = 38841;
UPDATE `locales_creature` SET `name_loc2` = 'Tortunok' , `subname_loc2` = 'Armures de druide' WHERE `entry` = 37992;
UPDATE `locales_creature` SET `name_loc2` = 'Gerardo le Mielleux' , `subname_loc2` = 'Armures de chasseur' WHERE `entry` = 37993;
UPDATE `locales_creature` SET `name_loc2` = 'Stefan Vadu' , `subname_loc2` = '' WHERE `entry` = 37589;
UPDATE `locales_creature` SET `name_loc2` = 'Généralissime Bolvar Fordragon' WHERE `entry` = 37183;
UPDATE `locales_creature` SET `name_loc2` = 'Commandant Kunz' , `subname_loc2` = '' WHERE `entry` = 37689;
UPDATE `locales_creature` SET `name_loc2` = 'Serviteur du Trône' WHERE `entry` = 36724;
UPDATE `locales_creature` SET `name_loc2` = 'Gardien de la couvée nérub\'ar' WHERE `entry` = 36725;
UPDATE `locales_creature` SET `name_loc2` = 'Entoilage' WHERE `entry` = 38028;
UPDATE `locales_creature` SET `name_loc2` = 'Wyrm de givre de la Flèche' WHERE `entry` = 37528;
UPDATE `locales_creature` SET `name_loc2` = 'Flamme froide' WHERE `entry` = 36672;
UPDATE `locales_creature` SET `name_loc2` = 'Domestique nécrorateur' , `subname_loc2` = 'Culte des damnés' WHERE `entry` = 36811;
UPDATE `locales_creature` SET `name_loc2` = 'Zélote nécrorateur' , `subname_loc2` = 'Culte des damnés' WHERE `entry` = 36808;
UPDATE `locales_creature` SET `name_loc2` = 'Serviteur nécrorateur' , `subname_loc2` = 'Culte des damnés' WHERE `entry` = 36805;
UPDATE `locales_creature` SET `name_loc2` = 'Pointe d\'os' WHERE `entry` = 36619;
UPDATE `locales_creature` SET `name_loc2` = 'Kalecgos' , `subname_loc2` = 'Ambassadeur du Vol draconique bleu' WHERE `entry` = 38017;
UPDATE `locales_creature` SET `name_loc2` = 'Myralion Solembrase' , `subname_loc2` = 'Les Saccage-soleil' WHERE `entry` = 36642;
UPDATE `locales_creature` SET `name_loc2` = 'Mage de guerre saccage-soleil' , `subname_loc2` = '' WHERE `entry` = 36657;
UPDATE `locales_creature` SET `name_loc2` = 'Caladis Brillelance' , `subname_loc2` = 'Le Concordat argenté' WHERE `entry` = 36624;
UPDATE `locales_creature` SET `name_loc2` = 'Sentinelle du Concordat argenté' , `subname_loc2` = '' WHERE `entry` = 36656;
UPDATE `locales_creature` SET `name_loc2` = 'Cible du crâne de Quel\'Delar' WHERE `entry` = 37852;
UPDATE `locales_creature` SET `name_loc2` = 'Drugan Grande-goulée' , `subname_loc2` = 'Ligue des explorateurs' WHERE `entry` = 37742;
UPDATE `locales_creature` SET `name_loc2` = 'Hippogriffe d\'Argent' WHERE `entry` = 37968;
UPDATE `locales_creature` SET `name_loc2` = 'Disciple nécrorateur' , `subname_loc2` = 'Culte des damnés' WHERE `entry` = 36807;
UPDATE `locales_creature` SET `name_loc2` = 'Grand prêtre nécrorateur' , `subname_loc2` = 'Culte des damnés' WHERE `entry` = 36829;
UPDATE `locales_creature` SET `name_loc2` = 'Dame Murmemort' WHERE `entry` = 36855;
UPDATE `locales_creature` SET `name_loc2` = 'Deathwhisper Spawn Stalker' WHERE `entry` = 37947;
UPDATE `locales_creature` SET `name_loc2` = 'Contrôleur Murmemort' WHERE `entry` = 37948;
UPDATE `locales_creature` SET `name_loc2` = 'Traqueur invisible' WHERE `entry` = 36848;
UPDATE `locales_creature` SET `name_loc2` = 'Serviteur nécrorateur ressuscité' WHERE `entry` = 36844;
UPDATE `locales_creature` SET `name_loc2` = 'Adhérent du culte' WHERE `entry` = 37949;
UPDATE `locales_creature` SET `name_loc2` = 'Fanatique du culte' , `subname_loc2` = 'Culte des damnés' WHERE `entry` = 37890;
UPDATE `locales_creature` SET `name_loc2` = 'Fanatique réanimé' , `subname_loc2` = 'Culte des damnés' WHERE `entry` = 38009;
UPDATE `locales_creature` SET `name_loc2` = 'Adhérent investi' WHERE `entry` = 38136;
UPDATE `locales_creature` SET `name_loc2` = 'Fanatique déformé' , `subname_loc2` = 'Culte des damnés' WHERE `entry` = 38135;
UPDATE `locales_creature` SET `name_loc2` = 'Adhérent réanimé' WHERE `entry` = 38010;
UPDATE `locales_creature` SET `name_loc2` = 'Ombre vengeresse' WHERE `entry` = 38222;
UPDATE `locales_creature` SET `name_loc2` = 'Défenseur kor\'kron' WHERE `entry` = 37032;
UPDATE `locales_creature` SET `name_loc2` = 'Traqueur kor\'kron' WHERE `entry` = 37028;
UPDATE `locales_creature` SET `name_loc2` = 'Nécrolyte kor\'kron' WHERE `entry` = 37149;
UPDATE `locales_creature` SET `name_loc2` = 'Redresseur de torts du Brise-ciel' WHERE `entry` = 37003;
UPDATE `locales_creature` SET `name_loc2` = 'Lame-d\'effroi du Brise-ciel' WHERE `entry` = 37004;
UPDATE `locales_creature` SET `name_loc2` = 'Oracle kor\'kron' WHERE `entry` = 37031;
UPDATE `locales_creature` SET `name_loc2` = 'Invocateur kor\'kron' WHERE `entry` = 37033;
UPDATE `locales_creature` SET `name_loc2` = 'Primaliste kor\'kron' WHERE `entry` = 37030;
UPDATE `locales_creature` SET `name_loc2` = 'Vainqueur kor\'kron' WHERE `entry` = 37035;
UPDATE `locales_creature` SET `name_loc2` = 'Sorcier du Brise-ciel' WHERE `entry` = 37026;
UPDATE `locales_creature` SET `name_loc2` = 'Invocatrice du Brise-ciel' WHERE `entry` = 37148;
UPDATE `locales_creature` SET `name_loc2` = 'Lumière du Brise-ciel' WHERE `entry` = 37016;
UPDATE `locales_creature` SET `name_loc2` = 'Vicaire du Brise-ciel' WHERE `entry` = 37021;
UPDATE `locales_creature` SET `name_loc2` = 'Tireur d\'élite du Brise-ciel' WHERE `entry` = 37144;
UPDATE `locales_creature` SET `name_loc2` = 'Hiérophante du Brise-ciel' WHERE `entry` = 37027;
UPDATE `locales_creature` SET `name_loc2` = 'Assassin du Brise-ciel' WHERE `entry` = 37017;
UPDATE `locales_creature` SET `name_loc2` = 'Protecteur du Brise-ciel' WHERE `entry` = 36998;
UPDATE `locales_creature` SET `name_loc2` = 'Wyrm de givre de la Flèche' WHERE `entry` = 37230;
UPDATE `locales_creature` SET `name_loc2` = 'Porte-mort Saurcroc' WHERE `entry` = 37813;
UPDATE `locales_creature` SET `name_loc2` = 'Rope Beam Stalker' WHERE `entry` = 37231;
UPDATE `locales_creature` SET `name_loc2` = 'Gargouille de la Flèche' WHERE `entry` = 37544;
UPDATE `locales_creature` SET `name_loc2` = 'Serviteur de la Flèche' WHERE `entry` = 37545;
UPDATE `locales_creature` SET `name_loc2` = 'Sniper kor\'kron' WHERE `entry` = 37146;
UPDATE `locales_creature` SET `name_loc2` = 'Etendard de bataille kor\'kron' WHERE `entry` = 37044;
UPDATE `locales_creature` SET `name_loc2` = 'Saccageur kor\'kron' WHERE `entry` = 37029;
UPDATE `locales_creature` SET `name_loc2` = 'Abomination frénétique' WHERE `entry` = 37546;
UPDATE `locales_creature` SET `name_loc2` = 'Equipage du Marteau d\'Orgrim' WHERE `entry` = 36971;
UPDATE `locales_creature` SET `name_loc2` = 'Marteau d\'Orgrim' WHERE `entry` = 37215;
UPDATE `locales_creature` SET `name_loc2` = 'Coque de la canonnière' WHERE `entry` = 37547;
UPDATE `locales_creature` SET `name_loc2` = 'Zone sûre (IGB)' WHERE `entry` = 37519;
UPDATE `locales_creature` SET `name_loc2` = 'Zafod Boîtaboum' WHERE `entry` = 37184;
UPDATE `locales_creature` SET `name_loc2` = 'Haut seigneur Saurcroc' WHERE `entry` = 36939;
UPDATE `locales_creature` SET `name_loc2` = 'Saccageur-des-cieux Korm Noire-balafre' WHERE `entry` = 37833;
UPDATE `locales_creature` SET `name_loc2` = 'Le Brise-ciel' WHERE `entry` = 37540;
UPDATE `locales_creature` SET `name_loc2` = 'Fusilier du Brise-ciel' WHERE `entry` = 36969;
UPDATE `locales_creature` SET `name_loc2` = 'Sorcier du Brise-ciel' WHERE `entry` = 37116;
UPDATE `locales_creature` SET `name_loc2` = 'Soldat-artilleur du Brise-ciel' WHERE `entry` = 36978;
UPDATE `locales_creature` SET `name_loc2` = 'Muradin Barbe-de-bronze' WHERE `entry` = 36948;
UPDATE `locales_creature` SET `name_loc2` = 'Traqueur de martyr (IGB/Saurcroc)' WHERE `entry` = 38569;
UPDATE `locales_creature` SET `name_loc2` = 'Portail de téléportation' WHERE `entry` = 37227;
UPDATE `locales_creature` SET `name_loc2` = 'Sergent du Brise-ciel' WHERE `entry` = 36961;
UPDATE `locales_creature` SET `name_loc2` = 'Soldat de marine du Brise-ciel' WHERE `entry` = 36950;
UPDATE `locales_creature` SET `name_loc2` = 'Sortie de téléportation' WHERE `entry` = 37488;
UPDATE `locales_creature` SET `name_loc2` = 'Saccageur kor\'kron' WHERE `entry` = 37920;
UPDATE `locales_creature` SET `name_loc2` = 'Bête de sang' WHERE `entry` = 38508;
UPDATE `locales_creature` SET `name_loc2` = 'Martyr Stalker (Reputation)' WHERE `entry` = 39010;
UPDATE `locales_creature` SET `name_loc2` = 'Péon chanteguerre' WHERE `entry` = 37930;
UPDATE `locales_creature` SET `name_loc2` = 'Morgan Feu-du-jour' , `subname_loc2` = 'Forgeron' WHERE `entry` = 37936;
UPDATE `locales_creature` SET `name_loc2` = 'Apothicaire Candith Tomas' , `subname_loc2` = 'Fournitures générales' WHERE `entry` = 37935;
UPDATE `locales_creature` SET `name_loc2` = 'Image de Noth le Porte-peste' WHERE `entry` = 37851;
UPDATE `locales_creature` SET `name_loc2` = 'Image du seigneur Gargamoelle' WHERE `entry` = 37864;
UPDATE `locales_creature` SET `name_loc2` = 'Frost Freeze Trap' WHERE `entry` = 37744;
UPDATE `locales_creature` SET `name_loc2` = 'Héraut val\'kyr' WHERE `entry` = 37098;
UPDATE `locales_creature` SET `name_loc2` = 'Abomination chancreuse' WHERE `entry` = 37022;
UPDATE `locales_creature` SET `name_loc2` = 'Scientifique de la peste' WHERE `entry` = 37023;
UPDATE `locales_creature` SET `name_loc2` = 'Horreur pustulée' WHERE `entry` = 10404;
UPDATE `locales_creature` SET `name_loc2` = 'Fauche-chair vengeur' WHERE `entry` = 37038;
UPDATE `locales_creature` SET `name_loc2` = 'Essence disjointe' WHERE `entry` = 38410;
UPDATE `locales_creature` SET `name_loc2` = 'Insecte pestiféré' WHERE `entry` = 38228;
UPDATE `locales_creature` SET `name_loc2` = 'Kifouette' WHERE `entry` = 37025;
UPDATE `locales_creature` SET `name_loc2` = 'Bijou' WHERE `entry` = 37217;
UPDATE `locales_creature` SET `name_loc2` = 'Archimage ténébrant' , `subname_loc2` = 'Les San\'layn' WHERE `entry` = 37664;
UPDATE `locales_creature` SET `name_loc2` = 'Piège de Putricide' WHERE `entry` = 38879;
UPDATE `locales_creature` SET `name_loc2` = 'Professeur Putricide' WHERE `entry` = 36678;
UPDATE `locales_creature` SET `name_loc2` = 'Colosse putréfié' WHERE `entry` = 36880;
UPDATE `locales_creature` SET `name_loc2` = 'Pulentraille' WHERE `entry` = 36626;
UPDATE `locales_creature` SET `name_loc2` = 'Trognepus' WHERE `entry` = 36627;
UPDATE `locales_creature` SET `name_loc2` = 'Zombie pesteux' WHERE `entry` = 38104;
UPDATE `locales_creature` SET `name_loc2` = 'Insecte mangeur de chair' WHERE `entry` = 37782;
UPDATE `locales_creature` SET `name_loc2` = 'Puddle Stalker' WHERE `entry` = 37013;
UPDATE `locales_creature` SET `name_loc2` = 'Traqueur de tentacule couvert de limon' WHERE `entry` = 38308;
UPDATE `locales_creature` SET `name_loc2` = 'Traqueur de tentacule visqueux' WHERE `entry` = 38309;
UPDATE `locales_creature` SET `name_loc2` = 'Ooze Spray Stalker' WHERE `entry` = 37986;
UPDATE `locales_creature` SET `name_loc2` = 'Petit limon' WHERE `entry` = 36897;
UPDATE `locales_creature` SET `name_loc2` = 'Gelée collante' WHERE `entry` = 37006;
UPDATE `locales_creature` SET `name_loc2` = 'Grand limon' WHERE `entry` = 36899;
UPDATE `locales_creature` SET `name_loc2` = 'Abomination Wing Mad Scientist Stalker' WHERE `entry` = 37824;
UPDATE `locales_creature` SET `name_loc2` = 'Fusilier torturé' WHERE `entry` = 38176;
UPDATE `locales_creature` SET `name_loc2` = 'Surveillant Kraggosh' , `subname_loc2` = '' WHERE `entry` = 36217;
UPDATE `locales_creature` SET `name_loc2` = 'Bragor Poing-de-sang' , `subname_loc2` = 'Capitaine kor\'kron' WHERE `entry` = 36273;
UPDATE `locales_creature` SET `name_loc2` = 'Aleric Hawkins' , `subname_loc2` = 'Les nécrotraqueurs' WHERE `entry` = 36517;
UPDATE `locales_creature` SET `name_loc2` = 'Dame Sylvanas Coursevent' , `subname_loc2` = 'Reine banshee' WHERE `entry` = 37223;
UPDATE `locales_creature` SET `name_loc2` = 'Le roi-liche' WHERE `entry` = 37226;
UPDATE `locales_creature` SET `name_loc2` = 'Falric' WHERE `entry` = 38112;
UPDATE `locales_creature` SET `name_loc2` = 'Marwyn' WHERE `entry` = 38113;
UPDATE `locales_creature` SET `name_loc2` = 'Prêtre fantomatique' WHERE `entry` = 38175;
UPDATE `locales_creature` SET `name_loc2` = 'Fantassin spectral' WHERE `entry` = 38173;
UPDATE `locales_creature` SET `name_loc2` = 'Mage fantôme' WHERE `entry` = 38172;
UPDATE `locales_creature` SET `name_loc2` = 'Mercenaire ténébreux' WHERE `entry` = 38177;
UPDATE `locales_creature` SET `name_loc2` = 'Hallucination fantôme' WHERE `entry` = 38567;
UPDATE `locales_creature` SET `name_loc2` = 'Forestier-sombre Loralen' WHERE `entry` = 37779;
UPDATE `locales_creature` SET `name_loc2` = 'Général lige-du-givre' WHERE `entry` = 36723;
UPDATE `locales_creature` SET `name_loc2` = 'Dame Sylvanas Coursevent' WHERE `entry` = 37554;
UPDATE `locales_creature` SET `name_loc2` = 'Le roi-liche' WHERE `entry` = 36954;
UPDATE `locales_creature` SET `name_loc2` = 'Canon de la canonnière de la Horde du donjon de la Couronne de glace' WHERE `entry` = 37593;
UPDATE `locales_creature` SET `name_loc2` = 'Cible du mur de glace' WHERE `entry` = 37014;
UPDATE `locales_creature` SET `name_loc2` = 'Traqueur invisible (piège du donjon de la Couronne de glace)' WHERE `entry` = 36736;
UPDATE `locales_creature` SET `name_loc2` = 'Invisible Stalker (Icecrown Dungeon Trap Controller)' WHERE `entry` = 37071;
UPDATE `locales_creature` SET `name_loc2` = 'Reflet spirituel' WHERE `entry` = 37068;
UPDATE `locales_creature` SET `name_loc2` = 'Reflet spirituel' WHERE `entry` = 37107;
UPDATE `locales_creature` SET `name_loc2` = 'Goule effrénée' WHERE `entry` = 36940;
UPDATE `locales_creature` SET `name_loc2` = 'Féticheur ressuscité' WHERE `entry` = 36941;
UPDATE `locales_creature` SET `name_loc2` = 'Abomination chancelante' WHERE `entry` = 37069;
UPDATE `locales_creature` SET `name_loc2` = 'Apparition malveillante' WHERE `entry` = 36551;
UPDATE `locales_creature` SET `name_loc2` = 'Moissonneur garde-âme' , `subname_loc2` = 'Culte des damnés' WHERE `entry` = 36499;
UPDATE `locales_creature` SET `name_loc2` = 'Ossomancien garde-âme' , `subname_loc2` = 'Culte des damnés' WHERE `entry` = 36564;
UPDATE `locales_creature` SET `name_loc2` = 'Adepte garde-âme' , `subname_loc2` = 'Culte des damnés' WHERE `entry` = 36620;
UPDATE `locales_creature` SET `name_loc2` = 'Animateur garde-âme' , `subname_loc2` = 'Culte des damnés' WHERE `entry` = 36516;
UPDATE `locales_creature` SET `name_loc2` = 'Horreur d\'âmes' WHERE `entry` = 36522;
UPDATE `locales_creature` SET `name_loc2` = 'Bronjahm' , `subname_loc2` = 'Parrain des âmes' WHERE `entry` = 36497;
UPDATE `locales_creature` SET `name_loc2` = 'Fragment d\'âme corrompue' WHERE `entry` = 36535;
UPDATE `locales_creature` SET `name_loc2` = 'Gardien spectral' WHERE `entry` = 36666;
UPDATE `locales_creature` SET `name_loc2` = 'Dévoreur d\'âmes' WHERE `entry` = 36502;
UPDATE `locales_creature` SET `name_loc2` = 'Puits des âmes' WHERE `entry` = 36536;
UPDATE `locales_creature` SET `name_loc2` = 'Ame déchaînée' WHERE `entry` = 36595;
UPDATE `locales_creature` SET `name_loc2` = 'Champion du colisée' WHERE `entry` = 37588;
UPDATE `locales_creature` SET `name_loc2` = 'Dame Sylvanas Coursevent' , `subname_loc2` = 'Reine banshee' WHERE `entry` = 38161;
UPDATE `locales_creature` SET `name_loc2` = 'Champion du colisée' WHERE `entry` = 37584;
UPDATE `locales_creature` SET `name_loc2` = 'Champion du colisée' WHERE `entry` = 37587;
UPDATE `locales_creature` SET `name_loc2` = 'Guerrier déchu' WHERE `entry` = 36841;
UPDATE `locales_creature` SET `name_loc2` = 'Gargouille échine-de-pierre' WHERE `entry` = 36896;
UPDATE `locales_creature` SET `name_loc2` = 'Proto-drake Né-de-glace' WHERE `entry` = 36891;
UPDATE `locales_creature` SET `name_loc2` = 'Oeil du roi-liche' WHERE `entry` = 36913;
UPDATE `locales_creature` SET `name_loc2` = 'Nécrolyte Murmemort' , `subname_loc2` = 'Culte des damnés' WHERE `entry` = 36788;
UPDATE `locales_creature` SET `name_loc2` = 'Exhalombre Murmemort' , `subname_loc2` = 'Culte des damnés' WHERE `entry` = 37712;
UPDATE `locales_creature` SET `name_loc2` = 'Tortionnaire Murmemort' , `subname_loc2` = 'Culte des damnés' WHERE `entry` = 37713;
UPDATE `locales_creature` SET `name_loc2` = 'Esclave squelettique' WHERE `entry` = 36881;
UPDATE `locales_creature` SET `name_loc2` = 'Seigneur du Fléau Tyrannus' WHERE `entry` = 36794;
UPDATE `locales_creature` SET `name_loc2` = 'Seigneur du Fléau Tyrannus' WHERE `entry` = 36658;
UPDATE `locales_creature` SET `name_loc2` = 'Maître-forge Gargivre' WHERE `entry` = 36494;
UPDATE `locales_creature` SET `name_loc2` = 'Dame Sylvanas Coursevent' , `subname_loc2` = 'Reine banshee' WHERE `entry` = 36990;
UPDATE `locales_creature` SET `name_loc2` = 'Esclave de la Horde' WHERE `entry` = 36770;
UPDATE `locales_creature` SET `name_loc2` = 'Champion corrompu' WHERE `entry` = 36796;
UPDATE `locales_creature` SET `name_loc2` = 'Ick' , `subname_loc2` = 'Serviteur de Krick' WHERE `entry` = 36476;
UPDATE `locales_creature` SET `name_loc2` = 'Travailleur Irossement' WHERE `entry` = 36830;
UPDATE `locales_creature` SET `name_loc2` = 'Goule affamée' WHERE `entry` = 37711;
UPDATE `locales_creature` SET `name_loc2` = 'Esclave de la Horde' WHERE `entry` = 36771;
UPDATE `locales_creature` SET `name_loc2` = 'Esclave de la Horde' WHERE `entry` = 36772;
UPDATE `locales_creature` SET `name_loc2` = 'Gorkun Crâne-de-fer' WHERE `entry` = 37592;
UPDATE `locales_creature` SET `name_loc2` = 'Esclave de la Horde' WHERE `entry` = 36773;
UPDATE `locales_creature` SET `name_loc2` = 'Mande-ciel ymirjar' WHERE `entry` = 31260;
UPDATE `locales_creature` SET `name_loc2` = 'Esclave de l\'Alliance' WHERE `entry` = 36764;
UPDATE `locales_creature` SET `name_loc2` = 'Esclave de l\'Alliance' WHERE `entry` = 36766;
UPDATE `locales_creature` SET `name_loc2` = 'Givrelame' WHERE `entry` = 37670;
UPDATE `locales_creature` SET `name_loc2` = 'Poliorcète Irossement' WHERE `entry` = 36907;
UPDATE `locales_creature` SET `name_loc2` = 'Esclave de l\'Alliance' WHERE `entry` = 36765;
UPDATE `locales_creature` SET `name_loc2` = 'Esclave de l\'Alliance' WHERE `entry` = 36767;
UPDATE `locales_creature` SET `name_loc2` = 'Esclave de la Horde libéré' WHERE `entry` = 37577;
UPDATE `locales_creature` SET `name_loc2` = 'Esclave de la Horde libéré' WHERE `entry` = 37578;
UPDATE `locales_creature` SET `name_loc2` = 'Esclave de la Horde libéré' WHERE `entry` = 37579;
UPDATE `locales_creature` SET `name_loc2` = 'Geist embusqué' WHERE `entry` = 36886;
UPDATE `locales_creature` SET `name_loc2` = 'Esclave de l\'Alliance secouru' WHERE `entry` = 36888;
UPDATE `locales_creature` SET `name_loc2` = 'Esclave de la Horde secouru' WHERE `entry` = 36889;
UPDATE `locales_creature` SET `name_loc2` = 'Krick' WHERE `entry` = 36477;
UPDATE `locales_creature` SET `name_loc2` = 'Horreur Peste-née' WHERE `entry` = 36879;
UPDATE `locales_creature` SET `name_loc2` = 'Matériel du Fléau' WHERE `entry` = 36983;
UPDATE `locales_creature` SET `name_loc2` = 'Orbe explosif' WHERE `entry` = 36610;
UPDATE `locales_creature` SET `name_loc2` = 'Frigecroc' WHERE `entry` = 36661;
UPDATE `locales_creature` SET `name_loc2` = 'Porte-mort ymirjar' WHERE `entry` = 36892;
UPDATE `locales_creature` SET `name_loc2` = 'Gorkun Crâne-de-fer' WHERE `entry` = 37581;
UPDATE `locales_creature` SET `name_loc2` = 'Porteflammes ymirjar' WHERE `entry` = 36893;
UPDATE `locales_creature` SET `name_loc2` = 'Porte-courroux ymirjar' WHERE `entry` = 36840;
UPDATE `locales_creature` SET `name_loc2` = 'Amefroide Irossement' WHERE `entry` = 36842;
UPDATE `locales_creature` SET `name_loc2` = 'Stalagtite s\'effondrant' WHERE `entry` = 36847;
UPDATE `locales_creature` SET `name_loc2` = 'Squelette Irossement' WHERE `entry` = 36877;
UPDATE `locales_creature` SET `name_loc2` = 'Revenant glaciaire perturbé' WHERE `entry` = 36874;
UPDATE `locales_creature` SET `name_loc2` = 'Saccageur Irossement' WHERE `entry` = 37729;
UPDATE `locales_creature` SET `name_loc2` = 'Ensorceleur Irossement' WHERE `entry` = 37728;
UPDATE `locales_creature` SET `name_loc2` = 'Guerrier déchu' WHERE `entry` = 38487;
UPDATE `locales_creature` SET `name_loc2` = 'Déflagration glaciale' WHERE `entry` = 36731;
UPDATE `locales_creature` SET `name_loc2` = 'Dame Sylvanas Coursevent' , `subname_loc2` = 'Reine banshee' WHERE `entry` = 38189;
UPDATE `locales_creature` SET `name_loc2` = 'Sindragosa' , `subname_loc2` = 'Reine des Couvegivres' WHERE `entry` = 37755;
UPDATE `locales_creature` SET `name_loc2` = 'Archimage Koreln' , `subname_loc2` = 'Kirin Tor' WHERE `entry` = 37582;
UPDATE `locales_creature` SET `name_loc2` = 'Archimage Elandra' , `subname_loc2` = 'Kirin Tor' WHERE `entry` = 37774;
UPDATE `locales_creature` SET `name_loc2` = 'Séide goule' WHERE `entry` = 36916;
UPDATE `locales_creature` SET `name_loc2` = 'Creuset des âmes' WHERE `entry` = 37094;
UPDATE `locales_creature` SET `name_loc2` = 'Dame Jaina Portvaillant' WHERE `entry` = 37597;
UPDATE `locales_creature` SET `name_loc2` = 'Dame Jaina Portvaillant' WHERE `entry` = 38160;
UPDATE `locales_creature` SET `name_loc2` = 'Dame Sylvanas Coursevent' , `subname_loc2` = 'Reine banshee' WHERE `entry` = 37596;
UPDATE `locales_creature` SET `name_loc2` = 'Forestier-sombre Kalira' WHERE `entry` = 37583;
UPDATE `locales_creature` SET `name_loc2` = 'Veilleur garde-âme' , `subname_loc2` = 'Culte des damnés' WHERE `entry` = 36478;
UPDATE `locales_creature` SET `name_loc2` = 'Champion du colisée' WHERE `entry` = 37496;
UPDATE `locales_creature` SET `name_loc2` = 'Champion du colisée' WHERE `entry` = 37497;
UPDATE `locales_creature` SET `name_loc2` = 'Champion du colisée' WHERE `entry` = 37498;
UPDATE `locales_creature` SET `name_loc2` = 'Martin Victus' WHERE `entry` = 37591;
UPDATE `locales_creature` SET `name_loc2` = 'Esclave de l\'Alliance libéré' WHERE `entry` = 37576;
UPDATE `locales_creature` SET `name_loc2` = 'Esclave de l\'Alliance libéré' WHERE `entry` = 37572;
UPDATE `locales_creature` SET `name_loc2` = 'Esclave de l\'Alliance libéré' WHERE `entry` = 37575;
UPDATE `locales_creature` SET `name_loc2` = 'Quel\'Delar' WHERE `entry` = 37158;
UPDATE `locales_creature` SET `name_loc2` = 'Dame Jaina Portvaillant' WHERE `entry` = 36955;
UPDATE `locales_creature` SET `name_loc2` = 'Dame Jaina Portvaillant' WHERE `entry` = 37221;
UPDATE `locales_creature` SET `name_loc2` = 'Uther le Porteur de Lumière' , `subname_loc2` = 'Chevalier de la Main d\'argent' WHERE `entry` = 37225;
UPDATE `locales_creature` SET `name_loc2` = 'Halduron Luisaile' , `subname_loc2` = 'Général des Forestiers' WHERE `entry` = 37527;
UPDATE `locales_creature` SET `name_loc2` = 'Shely Ferentrailles' , `subname_loc2` = 'Forgeron' WHERE `entry` = 37903;
UPDATE `locales_creature` SET `name_loc2` = 'Noble ténébrant' , `subname_loc2` = 'Les San\'layn' WHERE `entry` = 37663;
UPDATE `locales_creature` SET `name_loc2` = 'Chevalier de sang ténébrant' , `subname_loc2` = 'Les San\'layn' WHERE `entry` = 37595;
UPDATE `locales_creature` SET `name_loc2` = 'Lieutenant ténébrant' , `subname_loc2` = 'Les San\'layn' WHERE `entry` = 37665;
UPDATE `locales_creature` SET `name_loc2` = 'Commandant ténébrant' , `subname_loc2` = 'Les San\'layn' WHERE `entry` = 37662;
UPDATE `locales_creature` SET `name_loc2` = 'Commandant de l\'Alliance' WHERE `entry` = 37190;
UPDATE `locales_creature` SET `name_loc2` = 'Muradin Barbe-de-bronze' WHERE `entry` = 37200;
UPDATE `locales_creature` SET `name_loc2` = 'Brazie Kilah' , `subname_loc2` = 'Fournitures générales' WHERE `entry` = 37904;
UPDATE `locales_creature` SET `name_loc2` = 'Conseiller ténébrant' WHERE `entry` = 37571;
UPDATE `locales_creature` SET `name_loc2` = 'Prince Taldaram' WHERE `entry` = 37973;
UPDATE `locales_creature` SET `name_loc2` = 'Prince Valanar' WHERE `entry` = 37970;
UPDATE `locales_creature` SET `name_loc2` = 'Prince Keleseth' WHERE `entry` = 37972;
UPDATE `locales_creature` SET `name_loc2` = 'Valithria Marcherêve' WHERE `entry` = 36789;
UPDATE `locales_creature` SET `name_loc2` = '[The Lich King (Icecrown)]' WHERE `entry` = 29983;
UPDATE `locales_creature` SET `name_loc2` = 'Alana Heurtelune' , `subname_loc2` = 'Armures de druide' WHERE `entry` = 37999;
UPDATE `locales_creature` SET `name_loc2` = 'Alrin l\'Agile' WHERE `entry` = 38551;
UPDATE `locales_creature` SET `name_loc2` = 'Alchimiste Adrianna' , `subname_loc2` = '' WHERE `entry` = 38501;
UPDATE `locales_creature` SET `name_loc2` = 'Aronen' , `subname_loc2` = 'Apprenti d\'Ormus' WHERE `entry` = 39509;
UPDATE `locales_creature` SET `name_loc2` = 'Démon vampirique' WHERE `entry` = 37901;
UPDATE `locales_creature` SET `name_loc2` = 'Faucon de guerre' , `subname_loc2` = '' WHERE `entry` = 38154;
UPDATE `locales_creature` SET `name_loc2` = 'Valithria Marcherêve' WHERE `entry` = 38589;
UPDATE `locales_creature` SET `name_loc2` = 'Généralissime Tirion Fordring' , `subname_loc2` = '' WHERE `entry` = 38995;
UPDATE `locales_creature` SET `name_loc2` = 'Guerrier Gardegivre' WHERE `entry` = 37228;
UPDATE `locales_creature` SET `name_loc2` = 'Zombie purulent' WHERE `entry` = 37934;
UPDATE `locales_creature` SET `name_loc2` = 'Archimage ressuscité' WHERE `entry` = 37868;
UPDATE `locales_creature` SET `name_loc2` = 'Goule besogneuse' WHERE `entry` = 37695;
UPDATE `locales_creature` SET `name_loc2` = 'Esprit déchaîné' WHERE `entry` = 36701;
UPDATE `locales_creature` SET `name_loc2` = 'Ver pourri' WHERE `entry` = 37907;
UPDATE `locales_creature` SET `name_loc2` = 'Géant du givre pourrissant' WHERE `entry` = 38494;
UPDATE `locales_creature` SET `name_loc2` = 'Géant du givre pourrissant' WHERE `entry` = 38490;
UPDATE `locales_creature` SET `name_loc2` = 'Darnavan' WHERE `entry` = 38472;
UPDATE `locales_creature` SET `name_loc2` = 'Darnavan' WHERE `entry` = 38485;
UPDATE `locales_creature` SET `name_loc2` = 'Jedebia' , `subname_loc2` = 'Armures de chaman' WHERE `entry` = 38840;
UPDATE `locales_creature` SET `name_loc2` = 'Gardien des esprits' WHERE `entry` = 36824;
UPDATE `locales_creature` SET `name_loc2` = 'Insecte gelé' WHERE `entry` = 38229;
UPDATE `locales_creature` SET `name_loc2` = 'Insecte gelé' WHERE `entry` = 38370;
UPDATE `locales_creature` SET `name_loc2` = 'Ymirjar corrompu' WHERE `entry` = 38184;
UPDATE `locales_creature` SET `name_loc2` = 'Vierge combattante ymirjar' WHERE `entry` = 37132;
UPDATE `locales_creature` SET `name_loc2` = 'Chasseresse ymirjar' WHERE `entry` = 37134;
UPDATE `locales_creature` SET `name_loc2` = 'Lieuse-de-givre ymirjar' WHERE `entry` = 37127;
UPDATE `locales_creature` SET `name_loc2` = 'Porte-mort ymirjar' WHERE `entry` = 38125;
UPDATE `locales_creature` SET `name_loc2` = 'Seigneur de guerre ymirjar' WHERE `entry` = 37133;
UPDATE `locales_creature` SET `name_loc2` = 'Frigecroc' WHERE `entry` = 37533;
UPDATE `locales_creature` SET `name_loc2` = 'Squelette flamboyant' WHERE `entry` = 36791;
UPDATE `locales_creature` SET `name_loc2` = 'Yili' , `subname_loc2` = 'Armures de voleur' WHERE `entry` = 37997;
UPDATE `locales_creature` SET `name_loc2` = 'Maçon de l\'Alliance' WHERE `entry` = 37902;
UPDATE `locales_creature` SET `name_loc2` = 'Capitaine Arnath' , `subname_loc2` = '' WHERE `entry` = 37122;
UPDATE `locales_creature` SET `name_loc2` = 'Capitaine Brandon' , `subname_loc2` = '' WHERE `entry` = 37123;
UPDATE `locales_creature` SET `name_loc2` = 'Capitaine Grondel' , `subname_loc2` = '' WHERE `entry` = 37124;
UPDATE `locales_creature` SET `name_loc2` = 'Capitaine Rupert' , `subname_loc2` = '' WHERE `entry` = 37125;
UPDATE `locales_creature` SET `name_loc2` = 'Bombe cinétique' WHERE `entry` = 38454;
UPDATE `locales_creature` SET `name_loc2` = 'Ensorceleuse Gardegivre' WHERE `entry` = 37229;
UPDATE `locales_creature` SET `name_loc2` = 'Mage de bataille kor\'kron' WHERE `entry` = 37117;
UPDATE `locales_creature` SET `name_loc2` = 'Lieutenant kor\'kron' WHERE `entry` = 38491;
UPDATE `locales_creature` SET `name_loc2` = 'Lanceur de hache kor\'kron' WHERE `entry` = 36968;
UPDATE `locales_creature` SET `name_loc2` = 'Saccageur kor\'kron' WHERE `entry` = 36957;
UPDATE `locales_creature` SET `name_loc2` = 'Missilier kor\'kron' WHERE `entry` = 36982;
UPDATE `locales_creature` SET `name_loc2` = 'Sergent kor\'kron' WHERE `entry` = 36960;
UPDATE `locales_creature` SET `name_loc2` = 'Templier kor\'kron' WHERE `entry` = 37034;
UPDATE `locales_creature` SET `name_loc2` = 'Canon de la canonnière de l\'Alliance' WHERE `entry` = 36838;
UPDATE `locales_creature` SET `name_loc2` = 'Roi Varian Wrynn' , `subname_loc2` = 'Roi de Hurlevent' WHERE `entry` = 37879;
UPDATE `locales_creature` SET `name_loc2` = 'Pointe d\'os' WHERE `entry` = 38711;
UPDATE `locales_creature` SET `name_loc2` = 'Pointe d\'os' WHERE `entry` = 38712;
UPDATE `locales_creature` SET `name_loc2` = 'Parasite de sang' WHERE `entry` = 38231;
UPDATE `locales_creature` SET `name_loc2` = 'Araignée de sang' WHERE `entry` = 38232;
UPDATE `locales_creature` SET `name_loc2` = 'Crok Plaie-du-Fléau' , `subname_loc2` = 'Grand champion de la Lame d\'ébène' WHERE `entry` = 37129;
UPDATE `locales_creature` SET `name_loc2` = 'Dame Jaina Portvaillant' WHERE `entry` = 37188;
UPDATE `locales_creature` SET `name_loc2` = 'Dragonnet Aile-de-givre' WHERE `entry` = 37532;
UPDATE `locales_creature` SET `name_loc2` = 'Sphère de glace' WHERE `entry` = 36633;
UPDATE `locales_creature` SET `name_loc2` = 'Tombeau de glace' WHERE `entry` = 36980;
UPDATE `locales_creature` SET `name_loc2` = 'Lieutenant du Brise-ciel' WHERE `entry` = 38492;
UPDATE `locales_creature` SET `name_loc2` = 'Malfus Sombregivre' , `subname_loc2` = 'Armures de mage' WHERE `entry` = 38283;
UPDATE `locales_creature` SET `name_loc2` = 'Matelot du Brise-ciel' WHERE `entry` = 36970;
UPDATE `locales_creature` SET `name_loc2` = 'Démon vampirique investi' WHERE `entry` = 37919;
UPDATE `locales_creature` SET `name_loc2` = 'Rejeton nérub\'ar' WHERE `entry` = 37232;
UPDATE `locales_creature` SET `name_loc2` = 'Champion nérub\'ar' WHERE `entry` = 37501;
UPDATE `locales_creature` SET `name_loc2` = 'Tissetoile nérub\'ar' WHERE `entry` = 37502;
UPDATE `locales_creature` SET `name_loc2` = 'Limon volatil' WHERE `entry` = 37697;
UPDATE `locales_creature` SET `name_loc2` = 'Niby le Tout-puissant' , `subname_loc2` = 'Armures de démoniste' WHERE `entry` = 38182;
UPDATE `locales_creature` SET `name_loc2` = 'Nuage de gaz' WHERE `entry` = 37562;
UPDATE `locales_creature` SET `name_loc2` = 'Tacticien ténébrant' , `subname_loc2` = 'Les San\'layn' WHERE `entry` = 37666;
UPDATE `locales_creature` SET `name_loc2` = 'Marinier du Brise-ciel' WHERE `entry` = 37830;
UPDATE `locales_creature` SET `name_loc2` = 'Suppresseur' WHERE `entry` = 37863;
UPDATE `locales_creature` SET `name_loc2` = 'Portail onirique' WHERE `entry` = 37945;
UPDATE `locales_creature` SET `name_loc2` = 'Abomination gloutonne' WHERE `entry` = 37886;
UPDATE `locales_creature` SET `name_loc2` = 'Lance de perforation' WHERE `entry` = 38248;
UPDATE `locales_creature` SET `name_loc2` = 'Dresseur Gardegivre' WHERE `entry` = 37531;
UPDATE `locales_creature` SET `name_loc2` = 'Infiltrateur Minchar' WHERE `entry` = 38558;
UPDATE `locales_creature` SET `name_loc2` = 'Infiltrateur Minchar' WHERE `entry` = 38471;
UPDATE `locales_creature` SET `name_loc2` = 'Sœur Svalna' WHERE `entry` = 37126;
UPDATE `locales_creature` SET `name_loc2` = 'Grand capitaine Justin Bartlett' WHERE `entry` = 37182;
UPDATE `locales_creature` SET `name_loc2` = 'Talan Heurtelune' , `subname_loc2` = 'Armures de chasseur' WHERE `entry` = 37998;
UPDATE `locales_creature` SET `name_loc2` = 'Sombre Nucléus' WHERE `entry` = 38369;
UPDATE `locales_creature` SET `name_loc2` = 'Terenas Menethil' WHERE `entry` = 36823;
UPDATE `locales_creature` SET `name_loc2` = 'Bombe de gaz asphyxiant' WHERE `entry` = 38159;
UPDATE `locales_creature` SET `name_loc2` = 'Traquépine' WHERE `entry` = 37534;
UPDATE `locales_creature` SET `name_loc2` = 'Horreur titubante' WHERE `entry` = 37698;
UPDATE `locales_creature` SET `name_loc2` = 'Laquais de La Royale' WHERE `entry` = 37214;
UPDATE `locales_creature` SET `name_loc2` = 'Chariot de produits chimiques' WHERE `entry` = 38035;
UPDATE `locales_creature` SET `name_loc2` = 'Inspecteur Latenaille Tordboulon' WHERE `entry` = 38066;
UPDATE `locales_creature` SET `name_loc2` = 'Agent de relations publiques' , `subname_loc2` = 'Cie de Chimie La Royale' WHERE `entry` = 37675;
UPDATE `locales_creature` SET `name_loc2` = 'Marchande ravissante' , `subname_loc2` = 'Cie de Chimie La Royale' WHERE `entry` = 37674;
UPDATE `locales_creature` SET `name_loc2` = 'Kalin Colportecoeur' , `subname_loc2` = 'Cie de Chimie La Royale' WHERE `entry` = 37887;
UPDATE `locales_creature` SET `name_loc2` = 'Kalin Colportecoeur' , `subname_loc2` = 'Cie de Chimie La Royale' WHERE `entry` = 38042;
UPDATE `locales_creature` SET `name_loc2` = 'Kalin Colportecoeur' , `subname_loc2` = 'Cie de Chimie La Royale' WHERE `entry` = 38039;
UPDATE `locales_creature` SET `name_loc2` = 'Kalin Colportecoeur' , `subname_loc2` = 'Cie de Chimie La Royale' WHERE `entry` = 38040;
UPDATE `locales_creature` SET `name_loc2` = 'Kalin Colportecoeur' , `subname_loc2` = 'Cie de Chimie La Royale' WHERE `entry` = 38041;
UPDATE `locales_creature` SET `name_loc2` = 'Kalin Colportecoeur' , `subname_loc2` = 'Cie de Chimie La Royale' WHERE `entry` = 38043;
UPDATE `locales_creature` SET `name_loc2` = 'Kalin Colportecoeur' , `subname_loc2` = 'Cie de Chimie La Royale' WHERE `entry` = 38044;
UPDATE `locales_creature` SET `name_loc2` = 'Kalin Colportecoeur' , `subname_loc2` = 'Cie de Chimie La Royale' WHERE `entry` = 38045;
UPDATE `locales_creature` SET `name_loc2` = 'Inspecteur Lapince Tordboulon' WHERE `entry` = 37172;
UPDATE `locales_creature` SET `name_loc2` = 'Enquêteur Fezzen Desfaits' WHERE `entry` = 38208;
UPDATE `locales_creature` SET `name_loc2` = 'Apothicaire Hummel' , `subname_loc2` = 'Cie de Chimie La Royale' WHERE `entry` = 36296;
UPDATE `locales_creature` SET `name_loc2` = 'Apothicaire Baxter' , `subname_loc2` = 'Cie de Chimie La Royale' WHERE `entry` = 36565;
UPDATE `locales_creature` SET `name_loc2` = 'Apothicaire Frye' , `subname_loc2` = 'Cie de Chimie La Royale' WHERE `entry` = 36272;
UPDATE `locales_creature` SET `name_loc2` = 'Apothicaire affolé' WHERE `entry` = 36568;
UPDATE `locales_creature` SET `name_loc2` = 'Apothicaire de La Royale' WHERE `entry` = 36885;
UPDATE `locales_creature` SET `name_loc2` = 'Garde du matériel de La Royale' , `subname_loc2` = 'Cie de Chimie La Royale' WHERE `entry` = 37671;
UPDATE `locales_creature` SET `name_loc2` = 'Apprenti détective' WHERE `entry` = 38295;
UPDATE `locales_creature` SET `name_loc2` = 'Roka' WHERE `entry` = 38328;
UPDATE `locales_creature` SET `name_loc2` = 'Canot de l\'amour de Fossoyeuse' WHERE `entry` = 37966;
UPDATE `locales_creature` SET `name_loc2` = 'Chignard Rouillefusée' , `subname_loc2` = 'KapitalRisk' WHERE `entry` = 37715;
UPDATE `locales_creature` SET `name_loc2` = 'Chignard Rouillefusée' , `subname_loc2` = 'KapitalRisk' WHERE `entry` = 38334;
UPDATE `locales_creature` SET `name_loc2` = 'Chignard Rouillefusée' , `subname_loc2` = 'KapitalRisk' WHERE `entry` = 38335;
UPDATE `locales_creature` SET `name_loc2` = 'Chignard Rouillefusée' , `subname_loc2` = 'KapitalRisk' WHERE `entry` = 38336;
UPDATE `locales_creature` SET `name_loc2` = 'Canot de l\'amour de Darnassus' WHERE `entry` = 37980;
UPDATE `locales_creature` SET `name_loc2` = 'Marion Sutton' WHERE `entry` = 38325;
UPDATE `locales_creature` SET `name_loc2` = 'Canot de l\'amour de Hurlevent' WHERE `entry` = 36812;
UPDATE `locales_creature` SET `name_loc2` = 'Toravon la Sentinelle de glace' WHERE `entry` = 38433;
UPDATE `locales_creature` SET `name_loc2` = 'Gardien du givre' WHERE `entry` = 38482;
UPDATE `locales_creature` SET `name_loc2` = 'Ecton Briquedouille' , `subname_loc2` = 'Apprenti vendeur de l\'arène' WHERE `entry` = 33934;
UPDATE `locales_creature` SET `name_loc2` = 'Barrett Ramsey' , `subname_loc2` = 'Maître du colisée d\'Argent' WHERE `entry` = 35910;
UPDATE `locales_creature` SET `name_loc2` = 'Zom Bocom' , `subname_loc2` = 'Apprenti vendeur de l\'arène' WHERE `entry` = 33938;
UPDATE `locales_creature` SET `name_loc2` = 'Xazi Fumetuyère' , `subname_loc2` = 'Vendeuse de l\'arène' WHERE `entry` = 33937;
UPDATE `locales_creature` SET `name_loc2` = 'Nargle Cinglecorde' , `subname_loc2` = 'Vendeur de l\'arène vétéran' WHERE `entry` = 33936;
UPDATE `locales_creature` SET `name_loc2` = 'Dentos Rix' , `subname_loc2` = 'Armes d\'arène exceptionnelles' WHERE `entry` = 34095;
UPDATE `locales_creature` SET `name_loc2` = 'Dame Jaina Portvaillant' WHERE `entry` = 38188;
UPDATE `locales_creature` SET `name_loc2` = 'Garrosh Hurlenfer' , `subname_loc2` = 'Suzerain de l\'Offensive chanteguerre' WHERE `entry` = 39372;
UPDATE `locales_creature` SET `name_loc2` = 'Roi Varian Wrynn' , `subname_loc2` = 'Roi de Hurlevent' WHERE `entry` = 39371;
UPDATE `locales_creature` SET `name_loc2` = 'Grand Zokk Torquelada' , `subname_loc2` = 'Vendeur de l\'arène' WHERE `entry` = 33933;
UPDATE `locales_creature` SET `name_loc2` = 'Evee Cuivressort' , `subname_loc2` = 'Vendeuse de l\'arène' WHERE `entry` = 33935;
UPDATE `locales_creature` SET `name_loc2` = 'Argex Tripenfer' , `subname_loc2` = 'Vendeur de l\'arène vétéran' WHERE `entry` = 33939;
UPDATE `locales_creature` SET `name_loc2` = 'Kezzik le Frappeur' , `subname_loc2` = 'Vendeur de l\'arène vétéran' WHERE `entry` = 33940;
UPDATE `locales_creature` SET `name_loc2` = 'Leeni « Sourire » Smalls' , `subname_loc2` = 'Apprentie vendeuse de l\'arène' WHERE `entry` = 33941;
UPDATE `locales_creature` SET `name_loc2` = 'Sergent Corne-tonnerre' , `subname_loc2` = 'Intendant des armures apprenti' WHERE `entry` = 34038;
UPDATE `locales_creature` SET `name_loc2` = 'Dame Palanseer' , `subname_loc2` = 'Intendante de joaillerie' WHERE `entry` = 34043;
UPDATE `locales_creature` SET `name_loc2` = 'Doris Volanthius' , `subname_loc2` = 'Intendante des armures vétéran' WHERE `entry` = 34060;
UPDATE `locales_creature` SET `name_loc2` = 'Garde de sang Zar\'shi' , `subname_loc2` = 'Intendant des armures du Norfendre' WHERE `entry` = 34063;
UPDATE `locales_creature` SET `name_loc2` = 'Capitaine Mornemartel' , `subname_loc2` = 'Intendant des armures apprenti' WHERE `entry` = 34075;
UPDATE `locales_creature` SET `name_loc2` = 'Lieutenant Tristia' , `subname_loc2` = 'Intendante des armures vétéran' WHERE `entry` = 34078;
UPDATE `locales_creature` SET `name_loc2` = 'Capitaine O\'Neal' , `subname_loc2` = 'Intendant de joaillerie' WHERE `entry` = 34081;
UPDATE `locales_creature` SET `name_loc2` = 'Chevalier-lieutenant Heurtelune' , `subname_loc2` = 'Intendant des armures du Norfendre' WHERE `entry` = 34084;
UPDATE `locales_creature` SET `name_loc2` = 'Blazzek le Mordant' , `subname_loc2` = 'Armes d\'arène exceptionnelles' WHERE `entry` = 34093;
UPDATE `locales_creature` SET `name_loc2` = 'Grex Poêlaucrâne' , `subname_loc2` = 'Armes d\'arène exceptionnelles' WHERE `entry` = 34094;
UPDATE `locales_creature` SET `name_loc2` = 'Algalon Void Zone Visual Stalker' WHERE `entry` = 34100;
UPDATE `locales_creature` SET `name_loc2` = 'Le maître de poste' WHERE `entry` = 34337;
UPDATE `locales_creature` SET `name_loc2` = 'Chat calico' WHERE `entry` = 34364;
UPDATE `locales_creature` SET `name_loc2` = 'Burning Breath Koralon Stalker' WHERE `entry` = 35015;
UPDATE `locales_creature` SET `name_loc2` = 'Bruka Porte-malheur' , `subname_loc2` = 'Maître de guerre de l\'Île des Conquérants' WHERE `entry` = 35019;
UPDATE `locales_creature` SET `name_loc2` = 'Hurleuse de mort Gura' , `subname_loc2` = 'Maître de guerre de l\'Île des Conquérants' WHERE `entry` = 35020;
UPDATE `locales_creature` SET `name_loc2` = 'Marog' , `subname_loc2` = 'Maître de guerre de l\'Île des Conquérants' WHERE `entry` = 35021;
UPDATE `locales_creature` SET `name_loc2` = 'Souvenir de Chromaggus' WHERE `entry` = 35033;
UPDATE `locales_creature` SET `name_loc2` = 'Saboteur du Culte' , `subname_loc2` = 'Culte des damnés' WHERE `entry` = 35116;
UPDATE `locales_creature` SET `name_loc2` = 'Destrier d\'Argent' WHERE `entry` = 35179;
UPDATE `locales_creature` SET `name_loc2` = 'Mobile Burrow Target' WHERE `entry` = 35226;
UPDATE `locales_creature` SET `name_loc2` = 'Sessile Burrow Target' WHERE `entry` = 35227;
UPDATE `locales_creature` SET `name_loc2` = '[Relentless Gladiator\'s Frost Wyrm]' WHERE `entry` = 35362;
UPDATE `locales_creature` SET `name_loc2` = '[DND] Crazed Apothecary Generator' WHERE `entry` = 36212;
UPDATE `locales_creature` SET `name_loc2` = 'Cerf-volant rohart' WHERE `entry` = 36482;
UPDATE `locales_creature` SET `name_loc2` = 'Forgemaster Putridus Invisible Stalker' WHERE `entry` = 36495;
UPDATE `locales_creature` SET `name_loc2` = 'Soulguard Beam Focus Target' WHERE `entry` = 36508;
UPDATE `locales_creature` SET `name_loc2` = 'Bébé tigre spectral' WHERE `entry` = 36511;
UPDATE `locales_creature` SET `name_loc2` = '[DND] Valentine Boss - Vial Bunny' WHERE `entry` = 36530;
UPDATE `locales_creature` SET `name_loc2` = 'Beasts Combat Stalker' WHERE `entry` = 36549;
UPDATE `locales_creature` SET `name_loc2` = 'Le roi-liche' WHERE `entry` = 36597;
UPDATE `locales_creature` SET `name_loc2` = '[DND] Valentine Boss Manager' WHERE `entry` = 36643;
UPDATE `locales_creature` SET `name_loc2` = 'Abomination Wing Orange Gas Stalker' WHERE `entry` = 36659;
UPDATE `locales_creature` SET `name_loc2` = '[DND] Apothecary Table (Spell Effect)' WHERE `entry` = 36710;
UPDATE `locales_creature` SET `name_loc2` = '[DND] Love Boat Summoner' WHERE `entry` = 36817;
UPDATE `locales_creature` SET `name_loc2` = 'Sindragosa' , `subname_loc2` = 'Reine des Couvegivres' WHERE `entry` = 36853;
UPDATE `locales_creature` SET `name_loc2` = 'Jeune coursier du vent' WHERE `entry` = 36909;
UPDATE `locales_creature` SET `name_loc2` = 'Empowering Orb Controller Stalker' WHERE `entry` = 36934;
UPDATE `locales_creature` SET `name_loc2` = 'Apparition malveillante' WHERE `entry` = 36967;
UPDATE `locales_creature` SET `name_loc2` = 'Garde du Puits de soleil' , `subname_loc2` = '' WHERE `entry` = 36991;
UPDATE `locales_creature` SET `name_loc2` = 'Dame Jaina Portvaillant' WHERE `entry` = 36993;
UPDATE `locales_creature` SET `name_loc2` = 'Sunwell Visual Bunny' WHERE `entry` = 37000;
UPDATE `locales_creature` SET `name_loc2` = 'Etendard de bataille du Brise-ciel' WHERE `entry` = 37041;
UPDATE `locales_creature` SET `name_loc2` = 'Bombe de givre' WHERE `entry` = 37186;
UPDATE `locales_creature` SET `name_loc2` = 'Thalorien Cherchelaube' WHERE `entry` = 37205;
UPDATE `locales_creature` SET `name_loc2` = 'Défenseur du Puits de soleil' WHERE `entry` = 37211;
UPDATE `locales_creature` SET `name_loc2` = 'Pit of Saron Front Formation Bunny' WHERE `entry` = 37222;
UPDATE `locales_creature` SET `name_loc2` = 'Capitaine Arnath' WHERE `entry` = 37491;
UPDATE `locales_creature` SET `name_loc2` = 'Capitaine Brandon' WHERE `entry` = 37493;
UPDATE `locales_creature` SET `name_loc2` = 'Capitaine Grondel' WHERE `entry` = 37494;
UPDATE `locales_creature` SET `name_loc2` = 'Capitaine Rupert' WHERE `entry` = 37495;
UPDATE `locales_creature` SET `name_loc2` = 'Gardien de Sindragosa' WHERE `entry` = 37503;
UPDATE `locales_creature` SET `name_loc2` = 'Factionnaire du Soleil brisé' , `subname_loc2` = '' WHERE `entry` = 37509;
UPDATE `locales_creature` SET `name_loc2` = 'Archimage du Soleil brisé' , `subname_loc2` = '' WHERE `entry` = 37510;
UPDATE `locales_creature` SET `name_loc2` = 'Guerrier du Soleil brisé' , `subname_loc2` = '' WHERE `entry` = 37512;
UPDATE `locales_creature` SET `name_loc2` = 'Gardien du Puits de soleil' WHERE `entry` = 37523;
UPDATE `locales_creature` SET `name_loc2` = 'Zombie du Fléau' WHERE `entry` = 37538;
UPDATE `locales_creature` SET `name_loc2` = 'Goule envahisseuse' WHERE `entry` = 37539;
UPDATE `locales_creature` SET `name_loc2` = 'Ecumeur des cryptes' WHERE `entry` = 37541;
UPDATE `locales_creature` SET `name_loc2` = 'Morlen Poignefroide' WHERE `entry` = 37542;
UPDATE `locales_creature` SET `name_loc2` = 'Restes de Thalorien Cherchelaube' WHERE `entry` = 37552;
UPDATE `locales_creature` SET `name_loc2` = 'Abomination mutée' WHERE `entry` = 37672;
UPDATE `locales_creature` SET `name_loc2` = 'Flaque de limon croissante' WHERE `entry` = 37690;
UPDATE `locales_creature` SET `name_loc2` = 'Frostmourne Altar Bunny (Quel\'Delar)' WHERE `entry` = 37704;
UPDATE `locales_creature` SET `name_loc2` = 'Bâtisseur de Lune-d\'argent' WHERE `entry` = 37707;
UPDATE `locales_creature` SET `name_loc2` = 'Quel\'Delar' WHERE `entry` = 37745;
UPDATE `locales_creature` SET `name_loc2` = 'Sunwell Caster Bunny' WHERE `entry` = 37746;
UPDATE `locales_creature` SET `name_loc2` = 'Grand magistère Rommath' WHERE `entry` = 37763;
UPDATE `locales_creature` SET `name_loc2` = 'Lor\'themar Theron' , `subname_loc2` = 'Seigneur régent de Quel\'Thalas' WHERE `entry` = 37764;
UPDATE `locales_creature` SET `name_loc2` = 'Capitaine Auric Courresoleil' , `subname_loc2` = 'Représentant haut-elfe' WHERE `entry` = 37765;
UPDATE `locales_creature` SET `name_loc2` = 'Garde d\'honneur du Puits de soleil' WHERE `entry` = 37781;
UPDATE `locales_creature` SET `name_loc2` = 'Lapin de Tranchant de l\'ombre' WHERE `entry` = 37801;
UPDATE `locales_creature` SET `name_loc2` = 'Totem guérisseur' WHERE `entry` = 37810;
UPDATE `locales_creature` SET `name_loc2` = 'Lapin de hache Tranchant de l\'ombre' WHERE `entry` = 37814;
UPDATE `locales_creature` SET `name_loc2` = 'Vengeance de la lumière' WHERE `entry` = 37826;
UPDATE `locales_creature` SET `name_loc2` = 'Light\'s Vengeance Vehicle Bunny' WHERE `entry` = 37827;
UPDATE `locales_creature` SET `name_loc2` = 'Image de Thalorien Cherchelaube' WHERE `entry` = 37828;
UPDATE `locales_creature` SET `name_loc2` = 'Image d\'Alexstrasza' , `subname_loc2` = 'Reine des dragons' WHERE `entry` = 37829;
UPDATE `locales_creature` SET `name_loc2` = 'Lich King Stun Bunny' WHERE `entry` = 37832;
UPDATE `locales_creature` SET `name_loc2` = 'Image d\'Anasterian' WHERE `entry` = 37844;
UPDATE `locales_creature` SET `name_loc2` = 'Image de Morlen Poignefroide' WHERE `entry` = 37845;
UPDATE `locales_creature` SET `name_loc2` = 'Reine de sang Lana\'thel' , `subname_loc2` = 'Les San\'layn' WHERE `entry` = 37846;
UPDATE `locales_creature` SET `name_loc2` = 'Image de Sartharion' WHERE `entry` = 37849;
UPDATE `locales_creature` SET `name_loc2` = 'Image d\'Anub\'Rekhan' WHERE `entry` = 37850;
UPDATE `locales_creature` SET `name_loc2` = 'Image de l\'instructeur Razuvious' WHERE `entry` = 37853;
UPDATE `locales_creature` SET `name_loc2` = 'Image du Recousu' WHERE `entry` = 37854;
UPDATE `locales_creature` SET `name_loc2` = 'Image de Malygos' WHERE `entry` = 37855;
UPDATE `locales_creature` SET `name_loc2` = 'Le roi-liche' WHERE `entry` = 37857;
UPDATE `locales_creature` SET `name_loc2` = 'Image de Tranchécaille' WHERE `entry` = 37858;
UPDATE `locales_creature` SET `name_loc2` = 'Image d\'Ignis le maître de la Fournaise' WHERE `entry` = 37859;
UPDATE `locales_creature` SET `name_loc2` = 'Image du seigneur Jaraxxus' WHERE `entry` = 37862;
UPDATE `locales_creature` SET `name_loc2` = 'Event Fail Bunny' WHERE `entry` = 37871;
UPDATE `locales_creature` SET `name_loc2` = 'AoD Impact Bunny' WHERE `entry` = 37878;
UPDATE `locales_creature` SET `name_loc2` = 'Portail de Hurlevent' WHERE `entry` = 37880;
UPDATE `locales_creature` SET `name_loc2` = 'Goule déshéritée' WHERE `entry` = 37881;
UPDATE `locales_creature` SET `name_loc2` = 'Frax Foutriquet' , `subname_loc2` = 'Maître de vol' WHERE `entry` = 37888;
UPDATE `locales_creature` SET `name_loc2` = 'Vegard le Condamné' WHERE `entry` = 37893;
UPDATE `locales_creature` SET `name_loc2` = 'Lapin de Vegard' WHERE `entry` = 37894;
UPDATE `locales_creature` SET `name_loc2` = 'Ame emprisonnée' WHERE `entry` = 37906;
UPDATE `locales_creature` SET `name_loc2` = 'Timothy Cunningham' , `subname_loc2` = 'Éleveur de chauves-souris' WHERE `entry` = 37915;
UPDATE `locales_creature` SET `name_loc2` = 'Nervi de La Royale' WHERE `entry` = 37917;
UPDATE `locales_creature` SET `name_loc2` = 'Colonne de givre' WHERE `entry` = 37918;
UPDATE `locales_creature` SET `name_loc2` = 'Valithria Marcherêve' WHERE `entry` = 37950;
UPDATE `locales_creature` SET `name_loc2` = 'Light\'s Vengeance Vehicle Bunny 2' WHERE `entry` = 37952;
UPDATE `locales_creature` SET `name_loc2` = 'Reine de sang Lana\'thel' WHERE `entry` = 37955;
UPDATE `locales_creature` SET `name_loc2` = '[DND] Love Boat Summoner 02' WHERE `entry` = 37964;
UPDATE `locales_creature` SET `name_loc2` = 'Vegard le Condamné' WHERE `entry` = 37976;
UPDATE `locales_creature` SET `name_loc2` = '[DND] Love Boat Summoner 03' WHERE `entry` = 37981;
UPDATE `locales_creature` SET `name_loc2` = 'Epousseteur de La Royale' WHERE `entry` = 37984;
UPDATE `locales_creature` SET `name_loc2` = 'Nuage onirique' WHERE `entry` = 37985;
UPDATE `locales_creature` SET `name_loc2` = 'Vengeance de la lumière' WHERE `entry` = 38001;
UPDATE `locales_creature` SET `name_loc2` = 'Reine de sang Lana\'thel' WHERE `entry` = 38004;
UPDATE `locales_creature` SET `name_loc2` = 'Truand de La Royale' WHERE `entry` = 38006;
UPDATE `locales_creature` SET `name_loc2` = 'Contrôleur de l\'orbe de sang' WHERE `entry` = 38008;
UPDATE `locales_creature` SET `name_loc2` = 'Agent de La Royale' WHERE `entry` = 38016;
UPDATE `locales_creature` SET `name_loc2` = 'Arroseur de La Royale' WHERE `entry` = 38023;
UPDATE `locales_creature` SET `name_loc2` = 'Sous-fifre de La Royale' WHERE `entry` = 38030;
UPDATE `locales_creature` SET `name_loc2` = 'Diffuseur de La Royale' WHERE `entry` = 38032;
UPDATE `locales_creature` SET `name_loc2` = 'Pèlerin elfe de sang' WHERE `entry` = 38047;
UPDATE `locales_creature` SET `name_loc2` = 'Pèlerin haut-elfe' WHERE `entry` = 38048;
UPDATE `locales_creature` SET `name_loc2` = 'Dame Liadrin' , `subname_loc2` = 'Matriarche des chevaliers de sang' WHERE `entry` = 38052;
UPDATE `locales_creature` SET `name_loc2` = 'Chambellan Galiros' WHERE `entry` = 38056;
UPDATE `locales_creature` SET `name_loc2` = 'Sentinelle du matériel de La Royale' , `subname_loc2` = 'Cie de Chimie La Royale' WHERE `entry` = 38065;
UPDATE `locales_creature` SET `name_loc2` = 'Vide de mana' WHERE `entry` = 38068;
UPDATE `locales_creature` SET `name_loc2` = 'Unstable Ooze Explosion Stalker' WHERE `entry` = 38107;
UPDATE `locales_creature` SET `name_loc2` = 'Ombres grouillantes' WHERE `entry` = 38163;
UPDATE `locales_creature` SET `name_loc2` = 'Portail onirique' WHERE `entry` = 38186;
UPDATE `locales_creature` SET `name_loc2` = 'Tranchant de l\'ombre' WHERE `entry` = 38191;
UPDATE `locales_creature` SET `name_loc2` = 'Givrelame' WHERE `entry` = 38199;
UPDATE `locales_creature` SET `name_loc2` = 'Agent du Concordat argenté' , `subname_loc2` = '' WHERE `entry` = 38200;
UPDATE `locales_creature` SET `name_loc2` = 'Agent saccage-soleil' , `subname_loc2` = '' WHERE `entry` = 38201;
UPDATE `locales_creature` SET `name_loc2` = 'Déflagration glaciale' WHERE `entry` = 38223;
UPDATE `locales_creature` SET `name_loc2` = 'Déclencheur de flaque de limon croissante' WHERE `entry` = 38234;
UPDATE `locales_creature` SET `name_loc2` = 'Love Guard Perfume Bunny' WHERE `entry` = 38288;
UPDATE `locales_creature` SET `name_loc2` = 'Apprenti inspecteur' WHERE `entry` = 38293;
UPDATE `locales_creature` SET `name_loc2` = 'Ancien Clairdeleau' , `subname_loc2` = 'Pêcheur honoré' WHERE `entry` = 38294;
UPDATE `locales_creature` SET `name_loc2` = 'Tear Gas Target Stalker' WHERE `entry` = 38317;
UPDATE `locales_creature` SET `name_loc2` = 'Porte de la reine de sang' WHERE `entry` = 38319;
UPDATE `locales_creature` SET `name_loc2` = 'Boule de flammes' WHERE `entry` = 38332;
UPDATE `locales_creature` SET `name_loc2` = 'Chignard Rouillefusée' , `subname_loc2` = 'KapitalRisk' WHERE `entry` = 38337;
UPDATE `locales_creature` SET `name_loc2` = 'Chignard Rouillefusée' , `subname_loc2` = 'KapitalRisk' WHERE `entry` = 38338;
UPDATE `locales_creature` SET `name_loc2` = 'Chignard Rouillefusée' , `subname_loc2` = 'KapitalRisk' WHERE `entry` = 38339;
UPDATE `locales_creature` SET `name_loc2` = 'Gaspi toxique' WHERE `entry` = 38374;
UPDATE `locales_creature` SET `name_loc2` = 'Gardienne val\'kyr' WHERE `entry` = 38391;
UPDATE `locales_creature` SET `name_loc2` = 'Protectrice val\'kyr' WHERE `entry` = 38392;
UPDATE `locales_creature` SET `name_loc2` = 'Vortex de choc' WHERE `entry` = 38422;
UPDATE `locales_creature` SET `name_loc2` = 'Traqueur de Toravon' WHERE `entry` = 38439;
UPDATE `locales_creature` SET `name_loc2` = 'Boule de flammes infernales' WHERE `entry` = 38451;
UPDATE `locales_creature` SET `name_loc2` = 'Orbe gelé' WHERE `entry` = 38456;
UPDATE `locales_creature` SET `name_loc2` = 'Cible de la bombe cinétique' WHERE `entry` = 38458;
UPDATE `locales_creature` SET `name_loc2` = 'Toravon Frozen Orb Stalker' WHERE `entry` = 38461;
UPDATE `locales_creature` SET `name_loc2` = 'Empowering Orb Visual Stalker' WHERE `entry` = 38463;
UPDATE `locales_creature` SET `name_loc2` = 'Traqueur de rayon de Minchar' WHERE `entry` = 38557;
UPDATE `locales_creature` SET `name_loc2` = 'Black Knight Shield Proxy' WHERE `entry` = 38751;
UPDATE `locales_creature` SET `name_loc2` = 'Déclencheur de combat de dragon vert' WHERE `entry` = 38752;
UPDATE `locales_creature` SET `name_loc2` = 'Cadavre invoqué' WHERE `entry` = 38763;
UPDATE `locales_creature` SET `name_loc2` = 'Nervi de la vieille ville' WHERE `entry` = 38867;
UPDATE `locales_creature` SET `name_loc2` = 'Maréchal Magruder' , `subname_loc2` = 'Intendant de Joug-d\'hiver' WHERE `entry` = 39172;
UPDATE `locales_creature` SET `name_loc2` = 'Champion Ros\'slai' , `subname_loc2` = 'Intendant de Joug-d\'hiver' WHERE `entry` = 39173;
UPDATE `locales_creature` SET `name_loc2` = 'Erutor' , `subname_loc2` = 'Maître de guerre de l\'Île des Conquérants' WHERE `entry` = 35027;
UPDATE `locales_creature` SET `name_loc2` = 'Frozo l\'Illustre' , `subname_loc2` = 'Commerce des orbes gelés' WHERE `entry` = 40160;
UPDATE `locales_creature` SET `name_loc2` = 'Brutal Nether Drake' WHERE `entry` = 31124;
UPDATE `locales_creature` SET `name_loc2` = 'Palefroi céleste' WHERE `entry` = 40625;
UPDATE `locales_creature` SET `name_loc2` = 'Invincible' , `subname_loc2` = 'Ground Version' WHERE `entry` = 38545;
UPDATE `locales_creature` SET `name_loc2` = 'Fusée de tourisme X-53' WHERE `entry` = 40725;
UPDATE `locales_creature` SET `name_loc2` = 'Drake azur' WHERE `entry` = 31694;
UPDATE `locales_creature` SET `name_loc2` = '[Big Love Rocket]' WHERE `entry` = 38204;
UPDATE `locales_creature` SET `name_loc2` = 'Vainqueur couvegivre baigné de sang' WHERE `entry` = 38778;
UPDATE `locales_creature` SET `name_loc2` = 'Wyrm de givre du gladiateur furieux' WHERE `entry` = 34425;
UPDATE `locales_creature` SET `name_loc2` = 'Tête de Mimiron' WHERE `entry` = 33848;
UPDATE `locales_creature` SET `name_loc2` = 'Drake onyxien' WHERE `entry` = 36837;
UPDATE `locales_creature` SET `name_loc2` = 'Loup rapide de la Horde' WHERE `entry` = 35809;
UPDATE `locales_creature` SET `name_loc2` = 'Drake du Néant vengeur' WHERE `entry` = 27637;
UPDATE `locales_creature` SET `name_loc2` = 'Kieupid' , `subname_loc2` = 'Maître des familiers' WHERE `entry` = 40405;
UPDATE `locales_creature` SET `name_loc2` = 'Alenjon Lamesoleil' , `subname_loc2` = 'Maître de guerre' WHERE `entry` = 40413;
UPDATE `locales_creature` SET `name_loc2` = 'Chevalier-lieutenant T\'Maire Sydes' , `subname_loc2` = 'Intendant des armures du Norfendre' WHERE `entry` = 40607;
